name: lint
on:
  push:
    branches: [master]
  pull_request:
    branches-ignore:
      - "gh-pages"

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lunarmodules/luacheck@v1
        with:
          args: . --std luajit --globals vim _toggle_lazygit _command_panel _flash_esc_or_noh _debugging --max-line-length 150 --no-config
# ignore issue: https://luacheck.readthedocs.io/en/stable/inline.html?highlight=ignore#inline-options
